language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
install:
  - sudo apt-get install libgeos-dev
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
script: python -m pytest
notifications:
  email: false
